// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:f4944285-c6c3-4d02-8f5b-b9a2e6b35777',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '429e7b72f47040f6b99e3823a85fd517',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '597e7719-2616-4a0f-8ded-b950f66d7644',
    'aws_project_name': 'SEOgenie',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'seogenie-mobilehub-160717176',
}

export default awsmobile;
