(function (server) {
	var payload = [
		{keyword: 'auto seo', g: 4, y: 43, m: 102, category: {default: false, promoted:true, monitored: true, forced: true}, significance: 1, suitability: 2, activepages: 6},
		{keyword: 'auto seo optimization', g: 6, y: 5, m: 23, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 2, suitability: 3, activepages: 6},
		{keyword: 'auto seo tools', g: 3, y: 34, m: 423, category: {default: true, promoted:false, monitored: false, forced: true}, significance: 3, suitability: 4, activepages: 6},
		{keyword: 'Automated SEO', g: 1, y: 43, m: 102, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 4, suitability: 1, activepages: 6},
		{keyword: 'Automated SEO management', g: 23, y: 5, m: 23, category: {default: false, promoted:false, monitored: false, forced: true}, significance: 1, suitability: 2, activepages: 9},
		{keyword: 'automated seo services', g: 8, y: 34, m: 423, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 2, suitability: 3, activepages: 4},
		{keyword: 'automated seo tools', g: 2, y: 43, m: 102, category: {default: true, promoted:false, monitored: false, forced: true}, significance: 3, suitability: 4, activepages: 2},
		{keyword: 'automated seo websites', g: 1, y: 5, m: 23, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 4, suitability: 3, activepages: 6},
		{keyword: 'automated seo', g: 34, y: 34, m: 423, category: {default: true, promoted:false, monitored: false, forced: true}, significance: 1, suitability: 3, activepages: 6},
		{keyword: 'automated white hat seo', g: 5, y: 43, m: 102, category: {default: false, promoted:true, monitored: true, forced: true}, significance: 2, suitability: 3, activepages: 9},
		{keyword: 'Automatic Organic SEO', g: 2, y: 5, m: 23, category: {default: true, promoted:false, monitored: false, forced: true}, significance: 3, suitability: 1, activepages: 6},
		{keyword: 'automatic search engine optimization', g: 1, y: 34, m: 423, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 4, suitability: 3, activepages: 6},
		{keyword: 'Automatic SEO', g: 12, y: 43, m: 102, category: {default: true, promoted:false, monitored: false, forced: true}, significance: 1, suitability: 3, activepages: 5},
		{keyword: 'automatic seo free', g: 1, y: 5, m: 23, category: {default: true, promoted:true, monitored: true, forced: true}, significance: 2, suitability: 3, activepages: 6},
		{keyword: 'Automatic SEO service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Automatic SEO tools', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'automatic seo tools', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'automatic seo', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'automatic site promotion', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 4},
		{keyword: 'Best Automatic SEO service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best Automatic SEO solution', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best Automatic SEO system', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best SEO automation service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best SEO automation solution', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best Automatic SEO system', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best SEO automation service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 3},
		{keyword: 'Best SEO automation solution', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'Best SEO automation system', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 3},
		{keyword: 'best seo optimization firm', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 2},
		{keyword: 'check your web content to for seo optimization', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free automated seo tool', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free automated seo tools', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 1},
		{keyword: 'free automated seo', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free automatic seo software', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free keyword ranking', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 1},
		{keyword: 'free seo automation', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 0},
		{keyword: 'free seo ranking', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 0},
		{keyword: 'free SERP ranking', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free serp ranking service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free SERP ranking service', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'free web seo software', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'genie automatic site monitoring', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 6},
		{keyword: 'genie seo', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 2},
		{keyword: 'genie seo pro', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 3},
		{keyword: 'how to check web content to be seo optimised', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 0},
		{keyword: 'improve search engine rank', g: 14, y: 34, m: 423, category: {default: true, promoted:false, monitored: true, forced: true}, significance: 3, suitability: 2, activepages: 1}
	];
	server.add("api/keywords", payload, "GET", 200);
})(window.mockServer);